{
    "1178": {
        "commit": "e6a20043db694056ac00456f6076091012ecba87",
        "stack_trace": "java.lang.NullPointerException\n    at org.junit.internal.ArrayComparisonFailure.getMessage(ArrayComparisonFailure.java:52)\n    at org.junit.internal.ArrayComparisonFailure.toString(ArrayComparisonFailure.java:61)\n    at java.lang.String.valueOf(String.java:2982)\n    at java.io.PrintWriter.println(PrintWriter.java:754)\n    at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:764)\n    at java.lang.Throwable.printStackTrace(Throwable.java:655)\n    at java.lang.Throwable.printStackTrace(Throwable.java:721)\n    at org.gradle.api.internal.tasks.testing.junit.result.TestReportDataCollector.stackTrace(TestReportDataCollector.java:100)\n    at org.gradle.api.internal.tasks.testing.junit.result.TestReportDataCollector.afterTest(TestReportDataCollector.java:69)\n    at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)\n    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:497)\n    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)\n    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)\n    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)\n    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)\n    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)\n    at com.sun.proxy.$Proxy35.afterTest(Unknown Source)\n    at org.gradle.api.internal.tasks.testing.results.TestListenerAdapter.completed(TestListenerAdapter.java:48)\n    at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:65)\n    at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:52)\n    at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)\n    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:497)\n    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)\n    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)\n    at org.gradle.messaging.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)\n    at org.gradle.messaging.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:132)\n    at org.gradle.messaging.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:33)\n    at org.gradle.messaging.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:72)\n    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n    at java.lang.Thread.run(Thread.java:745)"
    },
    "1189": {
        "commit": "25495b3e91e346121e3292e8e01a3cc085b644f3",
        "stack_trace": "java.lang.Exception: No runnable methods\n    at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:202)\n    at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:138)\n    at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)\n    at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)\n    at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:68)\n    at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)\n    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)\n    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)\n    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)\n    at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)\n    at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)\n    at org.junit.runners.Suite.<init>(Suite.java:102)\n    at org.junit.runners.Suite.<init>(Suite.java:70)\n    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)\n    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)\n    at java.lang.reflect.Constructor.newInstance(Constructor.java:501)\n    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:108)\n    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)\n    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)\n    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)\n    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)\n    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)\n    at junit.framework.JUnit4TestAdapter.<init>(JUnit4TestAdapter.java:40)\n    at junit.framework.JUnit4TestAdapter.<init>(JUnit4TestAdapter.java:34)\n    at org.junit.tests.AllTests.suite(AllTests.java:246)"
    },
    "120": {
        "commit": "33fa8a845223e7bae46609cacce8e5d65d29de4c",
        "stack_trace": "java.lang.Exception: Unexpected exception, expected<java.lang.UnsupportedOperationException> but was<java.lang.AssertionError>\n    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)\n    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)\n    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)\n    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)\n    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)\n    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)\n    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)\n    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)"
    },
    "121": {
        "commit": "a25189631a9eb551a1ac961ca4d2c2db37a687a0",
        "stack_trace": "java.lang.Exception: Unexpected exception, expected<java.lang.UnsupportedOperationException> but was<java.lang.AssertionError>\n    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)\n    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)\n    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)\n    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)\n    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)\n    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)\n    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)\n    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)"
    },
    "1213": {
        "commit": "a25189631a9eb551a1ac961ca4d2c2db37a687a0",
        "stack_trace": "Caused by: java.security.AccessControlException: access denied (\"java.io.FilePermission\" \"/Users/trejkaz/junit.properties\" \"read\")\n    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)\n    at java.security.AccessController.checkPermission(AccessController.java:884)\n    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)\n    at java.lang.SecurityManager.checkRead(SecurityManager.java:888)\n    at java.io.FileInputStream.<init>(FileInputStream.java:127)\n    at junit.runner.BaseTestRunner.readPreferences(BaseTestRunner.java:232)\n    at junit.runner.BaseTestRunner.getPreferences(BaseTestRunner.java:51)\n    at junit.runner.BaseTestRunner.getPreference(BaseTestRunner.java:246)\n    at junit.runner.BaseTestRunner.getPreference(BaseTestRunner.java:250)\n    at junit.runner.BaseTestRunner.<clinit>(BaseTestRunner.java:324)"
    },
    "150": {
        "commit": "3289d9422b535666786aa3201ea0f31ad5e1f7e3",
        "stack_trace": "Exception in thread \"main\" java.lang.NoClassDefFoundError: org/junit/tests/AllTests (wrong name: lib/junit4.8.2/org/junit/tests/AllTests)\n    at java.lang.ClassLoader.defineClass1(Native Method)\n    at java.lang.ClassLoader.defineClass(ClassLoader.java:620)\n    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)\n    at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)\n    at java.net.URLClassLoader.access$100(URLClassLoader.java:56)\n    at java.net.URLClassLoader$1.run(URLClassLoader.java:195)\n    at java.security.AccessController.doPrivileged(Native Method)\n    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)\n    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)\n    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)\n    at java.lang.ClassLoader.loadClass(ClassLoader.java:251)\n    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)\n    at java.lang.Class.forName0(Native Method)\n    at java.lang.Class.forName(Class.java:164)\n    at org.junit.runner.JUnitCore.runMain(JUnitCore.java:89)\n    at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)\n    at org.junit.runner.JUnitCore.main(JUnitCore.java:45)'"
    },
    "209": {
        "commit": "36397848551f1dc843e4bf5036ff7b00b5cd6adb",
        "stack_trace": "Caused by: java.lang.IllegalStateException\n        at java.util.AbstractList$Itr.remove(AbstractList.java:356)\n        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:43)\n        at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:68)\n        at org.junit.runner.JUnitCore.run(JUnitCore.java:158)\n        at org.junit.runner.JUnitCore.run(JUnitCore.java:136)\n        at org.junit.runner.JUnitCore.run(JUnitCore.java:127)\n        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:51)\n        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:110)"
    },
    "257": {
        "commit": "ec6415e816b47eca315132bf4c3480424a61e740",
        "stack_trace": "java.lang.NullPointerException\n    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:36)\n    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:18)\n    at java.lang.reflect.Field.get(Field.java:358)\n    at org.junit.runners.model.FrameworkField.get(FrameworkField.java:48)\n    at org.junit.runners.ParentRunner.getClassRule(ParentRunner.java:212)\n    at org.junit.runners.ParentRunner.classRules(ParentRunner.java:206)\n    at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:194)\n    at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:153)\n    at org.junit.runners.ParentRunner.run(ParentRunner.java:304)\n    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)\n    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)"
    },
    "258": {
        "commit": "1f75796e4cd2827070f319d718ec4a8d285a9bdb",
        "stack_trace": "java.lang.RuntimeException: How did getAnnotatedFields return a field we couldn't access?\n    at org.junit.runners.ParentRunner.getClassRule(ParentRunner.java:214)\n    at org.junit.runners.ParentRunner.classRules(ParentRunner.java:206)\n    at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:194)\n    at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:153)\n    at org.junit.runners.ParentRunner.run(ParentRunner.java:304)\n    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)\n    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)\n    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)"
    },
    "74": {
        "commit": "80838a508b8875080c1b59d04f14ebaf74908af0",
        "stack_trace": "java.lang.NullPointerException\n at org.junit.runner.Description.createSuiteDescription(Description.java:"
    },
    "98": {
        "commit": "80838a508b8875080c1b59d04f14ebaf74908af0",
        "stack_trace": "java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<org.junit.internal.AssumptionViolatedException>\n    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)\n    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)\n    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)\n    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)\n    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)"
    }
}